### ISSUE TITLE
install.sh does not make the script executable

### ISSUE THREAD

**Issue by cheeesy** [autumnation/fuck#5]
## Description
After launching install.sh, the script is not made executable.

### Operating System
Arch Linux x86_64

### How to reproduce
`./install.sh` on a system where fuck is not yet installed.

### How to fix
I ran `chmod +x /usr/bin/fuck` to make it work in my terminal. Maybe there is a better way to achieve that and I am doing something horribly wrong. For me, however, the install script doesn't work out of the box.

**Comment by autumnation** [comment]
Sounds like the script is `fuck`ed up. @Chronomly

**Comment by Chronomly** [comment]
Okay I'll look into it

I'm gonna spin up a Arch VM

**Comment by autumnation** [comment]
Fixed with #8.
